FROM nginx:alpine AS stage1
LABEL maintainer="Lucas Grigolon Varela"
RUN echo "Welcome to Docker Labs!" > /opt/index.html

FROM nginx:alpine
LABEL maintainer="Lucas Grigolon Varela"
COPY --from=stage1 /opt/index.html /usr/share/nginx/html/
ENTRYPOINT ["nginx", "-g", "daemon off;"]