version: '3.1'
services:
   webserver:
     image: nginx:alpine
     expose:
       - "80"
   loadbalancer:
     image: nginx:alpine
     volumes:
       - ./nginx.conf:/etc/nginx/nginx.conf:ro
     depends_on:
       - webserver
     ports:
       - "80:4000"